app = "spyglasses-drupal-example"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/core/misc/drupal.js"
